plugins {
    id 'com.android.application'
}

def signingStoreFile = System.getenv("SIGNING_STORE_FILE")
def signingStorePassword = System.getenv("SIGNING_STORE_PASSWORD")
def signingKeyAlias = System.getenv("SIGNING_KEY_ALIAS")
def signingKeyPassword = System.getenv("SIGNING_KEY_PASSWORD")

android {
    namespace 'com.locutortts.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.locutortts.app"
        minSdk 29
        targetSdk 35
        versionCode 27
        versionName "1.27"
    }

    signingConfigs {
        release {
            if (signingStoreFile != null && !signingStoreFile.isEmpty()) {
                storeFile file(signingStoreFile)
                storePassword signingStorePassword
                keyAlias signingKeyAlias
                keyPassword signingKeyPassword
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
}
